### ISSUE TITLE
Implement autostart using background portal

### ISSUE THREAD

**Issue by tilosp** [flathub/com.nextcloud.desktopclient.nextcloud#18]
Maybe using https://github.com/matthiasclasen/libportal

**Comment by Verhoeckx** [comment]
What is the status of this issue?

At the moment `Launch on System Startup` of the Flatpak version of the Nextcloud Desktop app doesn't work. 
Will this be resolved in the near future?

**Comment by Akruidenberg** [comment]
same question for me

**Comment by curiousercreative** [comment]
This flatpak still does not autostart for me (Pop!_OS 22.04). How are others using this flatpak if it's not auto starting?

**Comment by curiousercreative** [comment]
Another update, apparently for my distro (and maybe yours) it's extremely trivial to enable autostart yourself. One liner that you can use once it's installed via flatpak (user install)
```
ln -s ~/.local/share/applications/com.nextcloud.desktopclient.nextcloud.desktop ~/.config/autostart/
```

**Comment by etam** [comment]
It should be this:
For `--user` installation:
```sh
ln -s ~/.local/share/flatpak/exports/share/applications/com.nextcloud.desktopclient.nextcloud.desktop ~/.config/autostart/
```

For `--system`:
```sh
ln -s /var/lib/flatpak/exports/share/applications/com.nextcloud.desktopclient.nextcloud.desktop ~/.config/autostart/
```

**Comment by FifthTundraG** [comment]
If we added a patch that does this then gave the app permissions to write to `xdg-config-dir/autostart` then we can enable autostart without using a portal. Many (including myself) would argue this is bad practice but it does undeniably _fix_ the issue without rewriting this whole function to use portals (which imo is a lot for a patch). Thoughts?

```diff
diff --git a/src/common/utility_unix.cpp b/src/common/utility_unix.cpp
index fc7d560..73caa36 100644
--- a/src/common/utility_unix.cpp
+++ b/src/common/utility_unix.cpp
@@ -100,14 +100,16 @@ void Utility::setLaunchOnStartup(const QString &appName, const QString &guiName,
         // When running inside an AppImage, we need to set the path to the
         // AppImage instead of the path to the executable
         const QString appImagePath = qEnvironmentVariable("APPIMAGE");
+        const QString flatpakId = qEnvironmentVariable("FLATPAK_ID");
         const bool runningInsideAppImage = !appImagePath.isNull() && QFile::exists(appImagePath);
-        const QString executablePath = runningInsideAppImage ? appImagePath : QCoreApplication::applicationFilePath();
+        const bool runningInsideFlatpak = !flatpakId.isNull();
+        const QString executablePath = runningInsideAppImage ? QLatin1String("\"%1\"").arg(appImagePath) : runningInsideFlatpak ? QLatin1String("flatpak run %1").arg(flatpakId) : QLatin1String("\"%1\"").arg(QCoreApplication::applicationFilePath());
 
         QTextStream ts(&iniFile);
         ts << QLatin1String("[Desktop Entry]\n")
            << QLatin1String("Name=") << guiName << QLatin1Char('\n')
            << QLatin1String("GenericName=") << QLatin1String("File Synchronizer\n")
-           << QLatin1String("Exec=\"") << executablePath << "\" --background\n"
+           << QLatin1String("Exec=") << executablePath << " --background\n"
            << QLatin1String("Terminal=") << "false\n"
            << QLatin1String("Icon=") << APPLICATION_ICON_NAME << QLatin1Char('\n')
            << QLatin1String("Categories=") << QLatin1String("Network\n")

```

**Comment by curiousercreative** [comment]
@FifthTundraG This effort seems to have stalled out or are we just missing the breadcrumb to find where the effort continues?

**Comment by FifthTundraG** [comment]
> @FifthTundraG This effort seems to have stalled out or are we just missing the breadcrumb to find where the effort continues?

I forgot about it ;D

Will try and get something across the finish line this week. No promises. Iirc I have a mostly functional implementation just missing an important detail or two.

**Comment by curiousercreative** [comment]
Maybe just a note for myself, but on COSMIC at least the user autostart files we discussed manually creating above don't consistently launch Nextcloud on login, seems to be some sort of race condition perhaps.

**Comment by curiousercreative** [comment]
Actually, it seems the autostart works consistently on first login after a boot. Logging out and logging back in yields this error in syslog: 
>nextcloud.gui.application: Already running, exiting...

`ps aux | grep nextcloud` yields nothing though and nextcloud starts fine from a launcher

UPDATE: Actually, autostarts on subsequent logins if you exit nextcloud prior to logout. If you don't do that, /run/user/1000/Nextcloud/socket sticks around and that seems to be why autostart fails.
